//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASiNet.App.RemoteKeyboard.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASiNet.App.RemoteKeyboard.Resources.Langs.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It was not possible to create a file containing data about this session, probably all unsaved data is irretrievably lost :(.
        /// </summary>
        internal static string BuilderCreateBackupErrorDescription {
            get {
                return ResourceManager.GetString("BuilderCreateBackupErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The session could not be saved.
        /// </summary>
        internal static string BuilderCreateBackupErrorTitle {
            get {
                return ResourceManager.GetString("BuilderCreateBackupErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data about the previous session will be uploaded and you can continue working..
        /// </summary>
        internal static string BuilderLoadPrevSessionDescription {
            get {
                return ResourceManager.GetString("BuilderLoadPrevSessionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load the previous session?.
        /// </summary>
        internal static string BuilderLoadPrevSessionTitle {
            get {
                return ResourceManager.GetString("BuilderLoadPrevSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For some reason, it was not possible to create a file, or write data to it. Try using a different file name and check the application permissions..
        /// </summary>
        internal static string BuilderSaveMessageErrorDescription {
            get {
                return ResourceManager.GetString("BuilderSaveMessageErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t save the keyboard.
        /// </summary>
        internal static string BuilderSaveMessageErrorTitle {
            get {
                return ResourceManager.GetString("BuilderSaveMessageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can close this page without fear of data loss..
        /// </summary>
        internal static string BuilderSaveMessageOkDescription {
            get {
                return ResourceManager.GetString("BuilderSaveMessageOkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The keyboard has been saved successfully.
        /// </summary>
        internal static string BuilderSaveMessageOkTitle {
            get {
                return ResourceManager.GetString("BuilderSaveMessageOkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter key name:.
        /// </summary>
        internal static string KeySelectorFilterPlaceholder {
            get {
                return ResourceManager.GetString("KeySelectorFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string KeySelectorOkButtonText {
            get {
                return ResourceManager.GetString("KeySelectorOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See more icons on the website fontawesome.com.
        /// </summary>
        internal static string KeySettingsMoreIconsText {
            get {
                return ResourceManager.GetString("KeySettingsMoreIconsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key options:.
        /// </summary>
        internal static string KeySettingsTitle {
            get {
                return ResourceManager.GetString("KeySettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancal.
        /// </summary>
        internal static string SaveKeyboardCancelButtonText {
            get {
                return ResourceManager.GetString("SaveKeyboardCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author(optional).
        /// </summary>
        internal static string SaveKeyboardQuestAuthorPlaceholder {
            get {
                return ResourceManager.GetString("SaveKeyboardQuestAuthorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description(optional).
        /// </summary>
        internal static string SaveKeyboardQuestDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("SaveKeyboardQuestDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string SaveKeyboardQuestTitlePlaceholder {
            get {
                return ResourceManager.GetString("SaveKeyboardQuestTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Keyboard:.
        /// </summary>
        internal static string SaveKeyboardQuestTitleText {
            get {
                return ResourceManager.GetString("SaveKeyboardQuestTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SaveKeyboardSeveButtonText {
            get {
                return ResourceManager.GetString("SaveKeyboardSeveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select key mode.
        /// </summary>
        internal static string SelectKeyModeButtonText {
            get {
                return ResourceManager.GetString("SelectKeyModeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select key mode.
        /// </summary>
        internal static string SelectKeyModeTitle {
            get {
                return ResourceManager.GetString("SelectKeyModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large.
        /// </summary>
        internal static string SelectLargeSize {
            get {
                return ResourceManager.GetString("SelectLargeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium.
        /// </summary>
        internal static string SelectMediumSize {
            get {
                return ResourceManager.GetString("SelectMediumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combination (one modifier).
        /// </summary>
        internal static string SelectMultiKey1 {
            get {
                return ResourceManager.GetString("SelectMultiKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combination (two modifiers).
        /// </summary>
        internal static string SelectMultiKey2 {
            get {
                return ResourceManager.GetString("SelectMultiKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single Key.
        /// </summary>
        internal static string SelectSingleKey {
            get {
                return ResourceManager.GetString("SelectSingleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small.
        /// </summary>
        internal static string SelectSmallSize {
            get {
                return ResourceManager.GetString("SelectSmallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sixe X.
        /// </summary>
        internal static string SetSizeXTitle {
            get {
                return ResourceManager.GetString("SetSizeXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sixe Y.
        /// </summary>
        internal static string SetSizeYTitle {
            get {
                return ResourceManager.GetString("SetSizeYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string SettingsAddressPlaceholder {
            get {
                return ResourceManager.GetString("SettingsAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        internal static string SettingsConnectButtonText {
            get {
                return ResourceManager.GetString("SettingsConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On the server side, there is a restriction on connecting with these permissions: RemoteKeyboardAccess.
        /// </summary>
        internal static string SettingsConnectResultAccessDenied {
            get {
                return ResourceManager.GetString("SettingsConnectResultAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        internal static string SettingsConnectResultConnecting {
            get {
                return ResourceManager.GetString("SettingsConnectResultConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        internal static string SettingsConnectResultFailed {
            get {
                return ResourceManager.GetString("SettingsConnectResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect login or password..
        /// </summary>
        internal static string SettingsConnectResultIncorrectData {
            get {
                return ResourceManager.GetString("SettingsConnectResultIncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out ot attempts count.
        /// </summary>
        internal static string SettingsConnectResultOutOfAttempts {
            get {
                return ResourceManager.GetString("SettingsConnectResultOutOfAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected.
        /// </summary>
        internal static string SettingsConnectResultSuccess {
            get {
                return ResourceManager.GetString("SettingsConnectResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout.
        /// </summary>
        internal static string SettingsConnectResultTimeout {
            get {
                return ResourceManager.GetString("SettingsConnectResultTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To connect, the computer and the mobile device must be on 1 LAN, and the RAC Service must be running on the computer.
        /// </summary>
        internal static string SettingsInfoLabel {
            get {
                return ResourceManager.GetString("SettingsInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string SettingsLoginPlaceholder {
            get {
                return ResourceManager.GetString("SettingsLoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string SettingsPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SettingsPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        internal static string SettingsPortPlaceholder {
            get {
                return ResourceManager.GetString("SettingsPortPlaceholder", resourceCulture);
            }
        }
    }
}
